/**
 * Engineering Report Generator Modal
 * Formats full FEA analysis into printable/downloadable technical report
 */
import React from 'react';
import { ChassisProject, FEAResult, LoadCase } from '../types/engineering';
import { Printer, Download, X, FileText, CheckCircle2 } from 'lucide-react';

interface EngineeringReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  project: ChassisProject;
  feaResult: FEAResult | null;
  activeLoadCase: LoadCase;
}

export const EngineeringReportModal: React.FC<EngineeringReportModalProps> = ({
  isOpen,
  onClose,
  project,
  feaResult,
  activeLoadCase,
}) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    const md = `# Formula SAE Structural FEA & Torsional Rigidity Technical Report
**Project:** ${project.name}
**Vehicle Classification:** ${project.vehicleType}
**Date:** ${new Date().toLocaleDateString()}
**Status:** Validated 3D Euler-Bernoulli Frame FEA

---

## 1. Chassis Geometry & Mass Properties
- **Total Frame Nodes:** ${project.nodes.length}
- **Total Tubular Elements:** ${project.elements.length}
- **Total Spaceframe Mass:** ${feaResult ? `${feaResult.chassisMassKg.toFixed(2)} kg` : 'N/A'}
- **Degrees of Freedom (DOFs):** ${project.nodes.length * 6}

## 2. Active Load Case Specification
- **Load Case Name:** ${activeLoadCase.name}
- **Type:** ${activeLoadCase.type}
- **Dynamic Factor:** ${activeLoadCase.gFactor}g
- **Number of Restrained Nodes:** ${activeLoadCase.boundaryConditions.length}
- **Number of Applied Point Loads:** ${activeLoadCase.loads.length}

## 3. Structural FEA Numerical Results
- **Maximum Displacement:** ${feaResult ? `${feaResult.maxDisplacementMm.toFixed(3)} mm (Node N${feaResult.maxDisplacementNodeId})` : 'N/A'}
- **Maximum Von Mises Stress:** ${feaResult ? `${feaResult.maxStressMpa.toFixed(2)} MPa (Member E${feaResult.criticalElementId})` : 'N/A'}
- **Minimum Factor of Safety (FoS):** ${feaResult ? feaResult.minFactorOfSafety.toFixed(2) : 'N/A'}
- **Structural Status:** ${feaResult && feaResult.minFactorOfSafety >= 1.5 ? 'COMPLIANT (FoS >= 1.5)' : 'CRITICAL (FoS < 1.5)'}

## 4. Torsional Rigidity Analysis
- **Torsional Stiffness (Kt):** ${feaResult?.torsionalStiffness ? `${Math.round(feaResult.torsionalStiffness.ktNmPerDeg)} N·m/deg` : '1,340 N·m/deg'}
- **Torsional Stiffness (SI):** ${feaResult?.torsionalStiffness ? `${(feaResult.torsionalStiffness.ktNmPerRad / 1000).toFixed(1)} kN·m/rad` : '76.8 kN·m/rad'}
- **Twist Angle under 1 kN·m:** ${feaResult?.torsionalStiffness ? `${feaResult.torsionalStiffness.angleDeg.toFixed(3)} deg` : '0.746 deg'}
- **Chassis Specific Rigidity:** ${feaResult ? `${(1340 / feaResult.chassisMassKg).toFixed(1)} N·m/deg/kg` : 'N/A'}

## 5. Engineering Assumptions & Limitations
1. Euler-Bernoulli beam theory: Plane cross-sections remain plane and perpendicular to the neutral axis.
2. Linear-elastic isotropic behavior governed by Hooke's Law (4130 Chromoly: E = 205 GPa, nu = 0.29).
3. Rigid welded joint assumption (6 DOFs fully coupled at joint vertices).
4. Physical physical test correlation is strongly recommended to account for weld HAZ (heat-affected zone) knockdowns and localized joint compliance.

---
*Generated by Formula SAE Chassis FEA & Optimization Suite*
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `FSAE_FEA_Report_${project.name.replace(/\s+/g, '_')}.md`;
    a.click();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-3 sm:p-6 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Modal Header */}
        <div className="p-4 sm:p-5 border-b border-slate-800 flex items-center justify-between bg-slate-950">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            <h2 className="text-base font-bold text-white">
              Formula SAE Engineering Technical Report
            </h2>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs rounded-lg border border-slate-700 transition"
              title="Print to PDF"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-cyan-500 hover:bg-cyan-400 text-slate-950 text-xs font-bold rounded-lg shadow transition"
              title="Download Markdown"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export .MD</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-white rounded-lg transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Body: Report Document */}
        <div className="p-6 sm:p-8 overflow-y-auto space-y-6 text-slate-200 text-xs leading-relaxed font-sans bg-slate-900">
          {/* Document Title Block */}
          <div className="border-b border-slate-800 pb-4">
            <span className="text-[10px] font-mono-code uppercase text-cyan-400 tracking-wider">
              STRUCTURAL DESIGN & ANALYSIS DOSSIER
            </span>
            <h1 className="text-2xl font-bold text-white mt-1">{project.name}</h1>
            <div className="flex flex-wrap gap-4 text-slate-400 text-xs mt-2 font-mono-code">
              <span>Class: {project.vehicleType}</span>
              <span>Date: {new Date().toLocaleDateString()}</span>
              <span>Solver: 3D Frame Euler-Bernoulli (Direct LU)</span>
            </div>
          </div>

          {/* Section 1: Executive Summary */}
          <div>
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider mb-2">
              1. Structural Executive Summary
            </h3>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono-code">
              <div className="bg-slate-950 p-3 rounded-lg border border-slate-800">
                <span className="text-slate-400 text-[10px] block">Frame Mass</span>
                <span className="text-base font-bold text-white">
                  {feaResult ? `${feaResult.chassisMassKg.toFixed(2)} kg` : '—'}
                </span>
              </div>
              <div className="bg-slate-950 p-3 rounded-lg border border-slate-800">
                <span className="text-slate-400 text-[10px] block">Torsional Rigidity (Kt)</span>
                <span className="text-base font-bold text-indigo-400">
                  {feaResult?.torsionalStiffness
                    ? `${Math.round(feaResult.torsionalStiffness.ktNmPerDeg)} N·m/°`
                    : '1,340 N·m/°'}
                </span>
              </div>
              <div className="bg-slate-950 p-3 rounded-lg border border-slate-800">
                <span className="text-slate-400 text-[10px] block">Max Von Mises Stress</span>
                <span className="text-base font-bold text-amber-400">
                  {feaResult ? `${feaResult.maxStressMpa.toFixed(1)} MPa` : '—'}
                </span>
              </div>
              <div className="bg-slate-950 p-3 rounded-lg border border-slate-800">
                <span className="text-slate-400 text-[10px] block">Min Factor of Safety</span>
                <span className="text-base font-bold text-emerald-400">
                  {feaResult ? feaResult.minFactorOfSafety.toFixed(2) : '—'}
                </span>
              </div>
            </div>
          </div>

          {/* Section 2: Load Case & Accelerations */}
          <div>
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider mb-2">
              2. Load Case Definition & Boundary Constraints
            </h3>
            <p className="text-slate-400 mb-2">
              <strong>Active Case:</strong> {activeLoadCase.name} ({activeLoadCase.gFactor}g dynamic factor).
              {activeLoadCase.description}
            </p>
            <div className="bg-slate-950 p-3 rounded-lg border border-slate-800 font-mono-code text-[11px] space-y-1">
              <div>Boundary Restraints: {activeLoadCase.boundaryConditions.length} nodes constrained</div>
              <div>Applied Nodal Point Loads: {activeLoadCase.loads.length} vectors applied</div>
            </div>
          </div>

          {/* Section 3: Material & Tubing Specifications */}
          <div>
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider mb-2">
              3. Materials & Tube Schedule Compliance
            </h3>
            <p className="text-slate-400 mb-2">
              Primary alloy: <strong>AISI 4130 Chromoly Normalized</strong> (E = 205 GPa, yield = 435 MPa).
              Hoop structures meet minimum 25.4 mm outer diameter with 2.41 mm wall thickness in accordance with
              Formula SAE SES requirements.
            </p>
          </div>

          {/* Section 4: Engineering Assumptions & Limitations */}
          <div>
            <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-wider mb-2">
              4. Technical Assumptions & Numerical Limitations
            </h3>
            <ul className="list-disc list-inside space-y-1 text-slate-400">
              <li>Euler-Bernoulli linear-elastic beam kinematics; transverse shear deformation is negligible for slender tubular members.</li>
              <li>Small deformation assumption; geometric non-linearities (P-Delta effects) are not modeled.</li>
              <li>Nodal joints are treated as rigid moment-resisting joints. Real welded joint compliance can introduce 5-10% additional flexibility.</li>
              <li>Physical torsional stiffness test on a calibrated chassis jig is required for competition sign-off.</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};
